- name: install  sql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: enable and start sql service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: setup password for mysql server
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1

