- name: install  sql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: enable and start sql service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: setup password for mysql server
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/frontend-robo{{ app_name }}:password token={{ token }} url=http://vault.yourtherapist.in:8200') }}


